### PR TITLE
Use embulk-api/spi:0.10.19 and embulk-util-config:0.1.4

### PR DESCRIPTION
**Pull request by dmikurube**

### CODE REVIEW

**Review by huylenq — APPROVED** [review]
LGTM

**Review by minidragon88 — APPROVED** [review]
LGTM.
But one minor concern is in https://github.com/embulk/embulk-input-mongodb/blob/master/.travis.yml#L33
we are using `embulk-0.9.23.jar` so should we update the `embulk` version in `travis`?

**Comment by minidragon88** [comment]
> LGTM.
> But one minor concern is in https://github.com/embulk/embulk-input-mongodb/blob/master/.travis.yml#L33
> we are using `embulk-0.9.23.jar` so should we update the `embulk` version in `travis`?

Please ignore my comment. Just see the PR https://github.com/embulk/embulk-input-mongodb/pull/61/files

**Comment by dmikurube** [comment]
Thanks! Yeah, but before GitHub Actions, we may want to test also with Embulk v0.10.19. I'll try. (I thought I included that change in this PR, but it has gone away, and maybe mixed in #61.)

**Comment by dmikurube** [comment]
@minidragon88 Jfyi, tested with Embulk v0.10.19 on Travis, and it's okay :)  : https://github.com/embulk/embulk-input-mongodb/pull/62

**Pull request merged**
